name: aug-lexical-negation
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - tqdm
  - datasets
  - evaluate
  - transformers
  - accelerate
  - spacy
  - pip:
    - --extra-index-url https://download.pytorch.org/whl/cu121
    - torch>=2.6
    - torchvision
    - torchaudio

  
